apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  volumes:
    - name: nginx-volume
      persistentVolumeClaim:
        claimName: local-pvc
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
        - mountPath: /var/www/html
          name: nginx-volume
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 128Mi
          cpu: "0.2"