apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu-sleeper-pod
  name: ubuntu-sleeper-pod
spec:
  containers:
  - image: ubuntu-sleeper
    name: ubuntu-sleeper
    imagePullPolicy: Never
    args: ["10"]
