apiVersion: batch/v1
kind: CronJob
metadata:
  name: dice
spec:
  schedule: '*/1 * * * *'
  jobTemplate:
    metadata:
      name: dice
    spec:
      template:
        spec:
          containers:
          - image: kodekloud/throw-dice
            name: dice
          restartPolicy: OnFailure
      completions: 1
      backoffLimit: 25
      activeDeadlineSeconds: 20