version: "3.8"

services:
  app:
    image: node:lts-alpine
    container_name: getting-started-on-mac
    # platform: linux/amd64
    command: sh -c "apk add --no-cache python2 g++ make && yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:5.7
    container_name: mysql-5.7
    # platform: linux/amd64
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  todo-mysql-data: