---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: custom-volume
spec:
  capacity:
    storage: 50Mi
  accessModes: ["ReadWriteMany"]
  hostPath:
    path: /opt/data​
  persistentVolumeReclaimPolicy: Retain