apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-analytics
spec:
  capacity:
    storage: 100Mi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/pv/data-analytics"