apiVersion: batch/v1
kind: Job
metadata:
 name: whalesay
spec:
 completions: 10
 backoffLimit: 6
 template:
   spec:
     containers:
     - command:
       - sh
       - -c
       - "cowsay I am going to ace CKAD!"
       image: docker/whalesay
       name: whalesay
     restartPolicy: Never