apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu
  name: ubuntu
  namespace: default
spec:
  containers:
  - image: ubuntu:latest
    name: ubuntu
    resources: {}
    command: ["sleep", "3600"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
